### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by yamabay** [yamabay/terraform_practice#10]
Task list of future improvements for the code:
- [ ] Remove hardcoded CIDR/subnets and move to referencing variable file
- [ ] Replicate resource creation in both regions so they are identical
- [ ] Modify naming standard so region names aren't hardcoded, allow for change of regions through variable file
